version: '3'
services:
  webdevcr-preview:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
     - VIRTUAL_HOST=webdevcr-preview.qingda.vm
    ports:
     - "5467:5467"
    volumes:
     - .:/usr/src/app
    command: bash -c 'cd /usr/src/app/_preview; sudo bundle update; ruby index.rb -o 0.0.0.0 -p 5467'
    image: jekyll:docker
    container_name: webdevcr-preview
  webdevcr:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
     - VIRTUAL_HOST=webdevcr.qingda.vm
     - CERT_NAME=qingda.vm
    ports:
     - "4000"
    volumes:
     - .:/usr/src/app
    command: bash -c 'cd /usr/src/app; jekyll serve -d _site --watch --host=0.0.0.0 --port 4000'
    image: jekyll:docker
    container_name: webdevcr
    external_links:
     - webdevcr-api:webdevcr-api.qingda.vm
networks:
  default:
    external:
      name: nginx-proxy
